### ISSUE TITLE
[BUG] K8s version selection not working anymore after deprecated V1 registry list tags API was removed from DockerHub

### ISSUE THREAD

**Issue by sfunkernw** [Xtigyro/kindadm#62]
K8s version selection not working anymore after [deprecated V1 registry list tags API](https://www.docker.com/blog/docker-hub-v1-api-deprecation/) was removed from DockerHub.

How to reproduce:

```bash
$ ./kindadm -n=2 -v=1.25.2 -hl='nodeType=devops' -ht -oa=weave-scope -cr

Unsupported K8s node version.
Supported versions:
```
The is a result of the wget command in https://github.com/Xtigyro/kindadm/blob/main/kindadm#L210 returning a HTTP 410 error.

Personally, I would fix it with:

```bash
...
declare -A k8s_vers_avail="$(wget -q https://registry.hub.docker.com/v2/repositories/kindest/node/tags?page_size=100 -O - | jq '."results"[]["name"]' )"
...
```
...however this introduces requirement for having `jq` installed (plus if more than 100 tags exist they wouldn't be fetched)...

**Comment by Xtigyro** [comment]
@sfunkernw It has been fixed in `main`. Thanks for the nice suggestion!
